### ISSUE TITLE
Data loss on large file transfers

### ISSUE THREAD

**Issue by NonstickAtom785** [TI-Planet/Project-Builder#5]
I might be abusing the virtual calc a little but when trying to send the 25 files required for Pokémon does not send all the data. .b84 bundles don't transfer either.

**Comment by adriweb** [comment]
Right, I haven't tried that much, although I don't see why it wouldn't work. Does it work when you do one by one?
Bundle files not transferring is expected, that's not supported because, well, it's not a usecare we care about for the emulated next to the IDE-integrated emulator...

Anyway, I'll close this considering the updated version of the CEmu core now supports real usb-based transfer emulation, so more things will be done properly. Not sure when I'll have time to update all that though. But it will be announced on tiplanet.
